isProd: true

namespace: prod

configmap:
  name: helmappconfigmap-prod
  data:
    CUSTOM_HEADER: "This app is running in Production!!!"
    BG_COLOR: '#000000'
    FONT_COLOR: '#FFFFFF'

image:
  name: nginx
  tag: latest         
  pullPolicy: IfNotPresent
  useConfig: true

service1:
  name: service-one
  useConfig: false

service2:
  name: service-two
  useConfig: true

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  host: prod.app.example.com
