isProd: false

namespace: staging

configmap:
  name: helmappconfigmap-staging
  data:
    CUSTOM_HEADER: "This is a Staging Environment!!!"
    BG_COLOR: '#003366'
    FONT_COLOR: '#FFFF00'

image:
  name: nginx
  tag: latest         
  pullPolicy: IfNotPresent
  useConfig: true

service1:
  name: service-one-staging
  useConfig: true

service2:
  name: service-two-staging
  useConfig: false

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

ingress:
  host: staging.app.example.com
