apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service2.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service2.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service2.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service2.name }}
    spec:
      containers:
      - name: "{{ .Values.service2.name }}-container"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
