{{- if .Values.service1.useConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  BG_COLOR: {{ .Values.configmap.data.BG_COLOR | quote }}
  FONT_COLOR: {{ .Values.configmap.data.FONT_COLOR | quote }}
  CUSTOM_HEADER: {{ if .Values.isProd }}"Welcome to the production version!"{{ else }}"This is a development environment."{{ end }}
{{- end }}
